src/Entity/Calendar.php
<?php

namespace App\Entity;

use App\Repository\CalendarRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CalendarRepository::class)
 */
class Calendar
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $start;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $end;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $all_day;

    /**
     * @ORM\Column(type="string", length=7, nullable=true)
     */
    private $background_color;

    /**
     * @ORM\Column(type="string", length=7, nullable=true)
     */
    private $border_color;

    /**
     * @ORM\Column(type="string", length=7, nullable=true)
     */
    private $text_color;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="prestations")
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity=Product::class, inversedBy="calendars")
     * @ORM\JoinColumn(nullable=false)
     */
    private $product;

    public function getId(): ?int
    {
        return $this->id;
    }


    public function getStart(): ?\DateTimeInterface
    {
        return $this->start;
    }

    public function setStart(\DateTimeInterface $start): self
    {
        $this->start = $start;

        return $this;
    }

    public function getEnd(): ?\DateTimeInterface
    {
        return $this->end;
    }

    public function setEnd(\DateTimeInterface $end): self
    {
        $this->end = $end;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getAllDay(): ?bool
    {
        return $this->all_day;
    }

    public function setAllDay(bool $all_day): self
    {
        $this->all_day = $all_day;

        return $this;
    }

    public function getBackgroundColor(): ?string
    {
        return $this->background_color;
    }

    public function setBackgroundColor(string $background_color): self
    {
        $this->background_color = $background_color;

        return $this;
    }

    public function getBorderColor(): ?string
    {
        return $this->border_color;
    }

    public function setBorderColor(string $border_color): self
    {
        $this->border_color = $border_color;

        return $this;
    }

    public function getTextColor(): ?string
    {
        return $this->text_color;
    }

    public function setTextColor(string $text_color): self
    {
        $this->text_color = $text_color;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(?Product $product): self
    {
        $this->product = $product;

        return $this;
    }
}

src/Form/CalendarType.php
<?php

namespace App\Form;

use App\Entity\Calendar;
use App\Entity\Product;
use App\Entity\User;
use App\Repository\ProductRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CalendarType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('product', EntityType::class,
                [
                    'label' => 'Choisir une prestation',
                    'class' => Product::class,
                    'query_builder' => function (ProductRepository $er) {
                        return $er->createQueryBuilder('p')
                            ->select('p')->innerJoin('p.categorie', 'c', 'with', 'c.name = :name')
                            ->setParameter('name', 'service');
                    },
                    'choice_label' => 'name',
                ])
            ->add('start', DateTimeType::class, [
                'date_widget' => 'single_text',
                'label' => "Choisir une date "

            ])
//            ->add('end', DateTimeType::class, [
//                'date_widget' => 'single_text'
//            ])
//            ->add('description', TextType::class, [
//                'label' => "Des spécifications : "
//            ])
//            ->add('all_day')
            // ->add('background_color', ColorType::class)
            // ->add('border_color',ColorType::class)
            // ->add('text_color',ColorType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Calendar::class,
        ]);
    }
}

src/Controller/CalendarController.php
<?php

namespace App\Controller;

use App\Entity\Calendar;
use App\Form\CalendarType;
use App\Notification\ContactNotification;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/calendar")
 */
class CalendarController extends AbstractController
{

    /**
     * @Route("/", name="calendar_index", methods={"GET"})
     */
    public function index(): Response
    {
        // $prestations = $this->getUser()->getPrestations();
        return $this->render('calendar/index.html.twig');
    }

    /**
     * @Route("/new", name="calendar_new", methods={"GET|POST"})
     * @param Request $request
     * @param ContactNotification $notification
     * @return Response
     */
    public function new(Request $request,  ContactNotification $notification): Response
    {
        $calendar = new Calendar();
        $calendar->setUser($this->getUser());
        $form = $this->createForm(CalendarType::class, $calendar);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($calendar);
            $entityManager->flush();
            $notification->sendResponse();
            return $this->redirectToRoute('calendar_index');
        }

        return $this->render('calendar/new.html.twig', [
            'calendar' => $calendar,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/{id}", name="calendar_show", methods={"GET"})
     */
    public function show(Calendar $calendar): Response
    {
        $user = $this->getUser();

        return $this->render('calendar/show.html.twig', [
            'calendar' => $calendar,
            'user'=>$user
        ]);
    }


    /**
     * @Route("/{id}/edit", name="calendar_edit", methods={"GET|POST"})
     */
    public function edit(Request $request, Calendar $calendar): Response
    {
        $form = $this->createForm(CalendarType::class, $calendar);
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('calendar_index');
        }

        return $this->render('calendar/edit.html.twig', [
            'calendar' => $calendar,
            'form' => $form->createView(),
        ]);
    }


    /**
     * @Route("/{id}", name="calendar_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Calendar $calendar): Response
    {
        if ($this->isTokenValid('delete' . $calendar->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($calendar);
            $entityManager->flush();
        }

        return $this->redirectToRoute('calendar_index');
    }
}

templates/calendar/_delete_form.html.twig
<form method="post" action="{{ path('calendar_delete', {'id': calendar.id}) }}" onsubmit="return confirm('Etes-vous sûre de supprimer l\élement ?');">

    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ calendar.id) }}">
    <button class="btn btn-danger btn-sm"><i class="fas fa-trash-alt"></i></button>
</form>

templates/calendar/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-sm" style="background-color: lightcoral; color: rebeccapurple; font-weight:500">{{ button_label|default('Valider') }}</button>
{{ form_end(form) }}

templates/calendar/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modification du calendrier Jade Beauty{% endblock %}

{% block body %}
    <h1>Modification du calandrier</h1>

    {{ include('calendar/_form.html.twig', {'button_label': 'Update'}) }}
    {{ include('calendar/_delete_form.html.twig') }}
<a class="btn btn-sm" href="{{ path('calendar_index') }}">retour à la liste</a>
{% endblock %}

templates/calendar/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Les prestations Jade Beauty
{% endblock %}

{% block body %}
    <h1>Nos réservations</h1>

    <table class="table" style="text-align: center">
        <thead>
        <tr>
            <th>Nom du client</th>
            <th>Prestations</th>
            {# <th>Nom du client</th> #}
            <th>Date et heure du rendez-vous</th>
            {# <th>End</th> #}
            {# <th>Description</th> #}
            {# <th>All_day</th> #}
            {# <th>Background_color</th> #}
            {# <th>Border_color</th> #}
            {# <th>Text_color</th> #}
            <th>Modifications</th>
        </tr>
        </thead>
        <tbody>
        {% for calendar in app.user.prestations %}
            <tr>
                <td>
                    {{ calendar.user.lastname }}
                </td>
                <td>
                    {{ calendar.product.name }}
                </td>
                <td>
                    {{ calendar.start ? calendar.start|date('d/m/Y H:i:s') : '' }}
                </td>
                {# <td>{{ calendar.description }}</td> #}
                {# <td>{{ calendar.end ? calendar.end|date('Y-m-d H:i:s') : '' }}</td> #}
                {# <td>{{ calendar.allDay ? 'Yes' : 'No' }}</td> #}
                {# <td>{{ calendar.backgroundColor }}</td> #}
                {# <td>{{ calendar.borderColor }}</td> #}
                {# <td>{{ calendar.textColor }}</td> #}
                <td>
                    <a href="{{ path('calendar_edit', {'id': calendar.id}) }}">
                        <img src="{{ asset('assets/image/icone/modifier.png') }}" alt="modifier mon produit" height="25px">
                    </a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">Pas de réservation trouvée</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <br>
    <div style="text-align: center">
        <a class="btn btn-sm" style="background-color: lightpink; color: rebeccapurple" href="{{ path('calendar_new') }}">Ajouter une réservation</a>
    </div>
{% endblock %}

templates/calendar/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Rendez-vous{% endblock %}

{% block body %}
    <div class="container">

        <div class="row">
            <div class="col-md-6">
                <h1>Prendre un rendez-vous</h1>
                <div class="input-group mb-5">
                    {{ include('calendar/_form.html.twig') }}
                </div>
                <a href="{{ path('calendar_index') }}">back to list</a>
            </div>
            {# <div class="col-md-6"> #}
            {# <div class="input-group mb-5"> #}
            {# <div id="calendrier"></div> #}
            {# </div> #}
            {# </div> #}
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    <script>
        window.onload = () => {
            let calendarElement = document.querySelector("#calendrier")
            let calendar = new FullCalendar.Calendar(calendarElement, {
                initialView: 'dayGridMonth',
                locale: 'fr',
                timeZone: 'Europe/Paris',
                headerToolbar: {
                    start: 'prev,next today',
                    center: 'title',
                    end: 'dayGridMonth,timeGridWeek',
                },
                {# events: {{ data|raw }}, #}
                editable: true,
                eventResizableFromStart: true,
                slotDuration: '1:00',
                defaultView: 'agendaWeek',
                selectable: true,
                selectHelper: true,
                eventLimit: true,
                slotEventOverlap: false,
                eventOverlap: false,
                minTime: '9:00:00',
                maxTime: '19:00:00',
                allDaySlot: false

            })

            calendar.on('eventChange', (e) => {
                //console.log(e)
                let url = `/api/${e.event.id}/edit`
                let donnees = {
                    'title': e.event.title,
                    'description': e.event.extendedProps.description,
                    'start': e.event.start,
                    'end': e.event.end,
                    'backgroundColor': e.event.backgroundColor,
                    'borderColor': e.event.borderColor,
                    'textColor': e.event.textColor,
                    'allDay': e.event.allDay,

                }
                //console.log(donnees)
                let xhr = new XMLHttpRequest
                xhr.open("PUT", url)
                xhr.send(JSON.stringify(donnees))
            })
            calendar.render()
        }
    </script>
{% endblock %}

templates/calendar/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Calendar{% endblock %}

{% block body %}
    <h1>Calendar</h1>

    <table class="table">
        <tbody>
        <tr>
            <th>Id</th>
            <td>{{ calendar.id }}</td>
        </tr>
        <tr>
            <th>Prestation</th>
            <td>{{ calendar.product.name }}</td>
        </tr>
        <tr>
            <th>Date</th>
            <td>{{ calendar.start ? calendar.start|date('d/m/Y H:i:s') : '' }}</td>
        </tr>
        {# <tr> #}
        {# <th>End</th> #}
        {# <td>{{ calendar.end ? calendar.end|date('Y-m-d H:i:s') : '' }}</td> #}
        {# </tr> #}
        <tr>
            <th>Spécifications</th>
            <td>{{ calendar.description }}</td>
        </tr>
        {# <tr> #}
        {# <th>All_day</th> #}
        {# <td>{{ calendar.allDay ? 'Yes' : 'No' }}</td> #}
        {# </tr> #}
        {# <tr> #}
        {# <th>Background_color</th> #}
        {# <td>{{ calendar.backgroundColor }}</td> #}
        {# </tr> #}
        {# <tr> #}
        {# <th>Border_color</th> #}
        {# <td>{{ calendar.borderColor }}</td> #}
        {# </tr> #}
        {# <tr> #}
        {# <th>Text_color</th> #}
        {# <td>{{ calendar.textColor }}</td> #}
        {# </tr> #}
        </tbody>
    </table>

    <div class="justify-content-center">
    <button class="btn btn-sm" style="background-color: lightpink; color: rebeccapurple;">
        <a href="{{ path('calendar_new') }}">Ajouter une réservation</a>
    </button>


    <a href="{{ path('calendar_index') }}">Retour à la liste</a>
    </div>
{% endblock %}